### PR TITLE
Make gender neutral

### PR DESCRIPTION
**Pull request by drewnoakes**

### CODE REVIEW

**Comment by jzabroski** [comment]
@drewnoakes This does not make it gender neutral.  "author"/"their" violates Subject/pronoun agreement.

**Comment by jzabroski** [comment]
@drewnoakes  This should be author/his or her

**Comment by drewnoakes** [comment]
> This does not make it gender neutral

Yes it does. Before it was masculine. With this change no gender is denoted.

> This should be author/his or her

In theory, but not in practice. Native speakers use "their" regularly for an individual whose gender is unknown or unspecified. I find "his or her" a mouthful.

There's some relevant discussion here https://english.stackexchange.com/q/192/3794

**Comment by sidristij** [comment]
Thank you very much for the fix!

**Comment by drewnoakes** [comment]
@sidristij that's interesting! I hadn't considered how that could happen during translation.

**Pull request merged**
